### ISSUE TITLE
Increase number of rows to use to detect column types

### ISSUE THREAD

**Issue by xiaodaigh** [bicycle1885/TableReader.jl#12]
Increasing the number rows to read before detecting type, some types are not detected correct in 

```julia
download("https://github.com/xiaodaigh/testing/raw/master/Performance_2016Q1.zip", "ok.zip")

run(`unzip ok.zip`)
using TableReader
path = "Performance_2016Q1.csv"
@time a = readcsv(path, delim = '|', chunksize = 0, colnames = [Symbol("var_$i") for i in 1:31]);
```

**Comment by bicycle1885** [comment]
Do you mean we should increase the default number of rows used to guess types? I think the current default value (1 MiB) is reasonably large and works well in most cases. Even if it didn't work, you can quickly change the value by `chunksize`.

**Comment by xiaodaigh** [comment]
I do chunk size = 0.

**Comment by bicycle1885** [comment]
And still you see the same error?

**Comment by xiaodaigh** [comment]
Yep. Type detection isn't correct. One column was detected as missing but
it should be a number. I will find the types and show u.

**Comment by bicycle1885** [comment]
Hmm, I think the problem has been fixed by ba1eab99f2b4d91aac96f456ae4f8d40d6fbb9e7 and #14 improves the type guessing further.

**Comment by xiaodaigh** [comment]
```julia
download("https://github.com/xiaodaigh/testing/raw/master/Performance_2016Q1.zip", "ok.zip")

run(`unzip ok.zip`)
using TableReader
path = "Performance_2016Q1.csv"
@time a = readcsv(path, delim = '|', chunksize = 0, colnames = [Symbol("var_$i") for i in 1:31]);
eltype.(a[:,i] for i in 1:size(a,2)))
``` 

returns some columns that are just `Missing`. This is clearly not correct. So I don't think it's been fixed yet.

**Comment by bicycle1885** [comment]
Can you clarify the expected behavior and what you see more clearly? I've tried TableReader.jl and two independent CSV parsers (pandas and xsv), and all the three say that column 20, 25, 28, and 30 are all missing.

```
julia> df = readcsv("data/Performance_2016Q1.csv", delim = '|', chunksize = 0, colnames = [Symbol("var_$i") for i in 1:31]);

julia> [(j, eltype(df[j])) for j in 1:size(df, 2)]
31-element Array{Tuple{Int64,Type},1}:
 (1, Int64)
 (2, String)
 (3, Union{Missing, String})
 (4, Float64)
 (5, Union{Missing, Float64})
 (6, Int64)
 (7, Int64)
 (8, Union{Missing, Int64})
 (9, String)
 (10, String)
 (11, Union{Missing, String})
 (12, String)
 (13, Union{Missing, String})
 (14, Union{Missing, String})
 (15, Union{Missing, String})
 (16, Union{Missing, String})
 (17, Union{Missing, String})
 (18, Union{Missing, Float64})
 (19, Union{Missing, Float64})
 (20, Missing)
 (21, Union{Missing, Float64})
 (22, Union{Missing, Float64})
 (23, Union{Missing, Float64})
 (24, Union{Missing, Float64})
 (25, Missing)
 (26, Union{Missing, Float64})
 (27, Union{Missing, Float64})
 (28, Missing)
 (29, Union{Missing, String})
 (30, Missing)
 (31, Union{Missing, String})

```

```
In [12]: df = pandas.read_csv("data/Performance_2016Q1.csv", sep='|', names=None, low_memory=False)

In [13]: for j in [20, 25, 28, 30]:
    ...:     print(j, all(pandas.isna(df.iloc[:,j-1])))
    ...:
20 True
25 True
28 True
30 True
```

```
~/w/TableReader (master|…) $ for col in 20 25 28 30
                                 echo col=$col
                                 xsv select -n -d'|' $col data/Performance_2016Q1.csv | uniq
                             end
col=20
""
col=25
""
col=28
""
col=30
""
```

**Comment by xiaodaigh** [comment]
You are right! They are all missing! I only read one month worth of files but there are like 10 years worth. So the one I've shown actually doesn't have any vlaues in those columns so your parser is absolutely correct!

r```
Performance_ColClasses = 
  c("character", "character", "character", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "character", "character", "character", "character", "character", "character", 
    "character", "character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "character", "numeric", 
    "character")
```
these are the types provided by the official source.

**Comment by bicycle1885** [comment]
Okay, so I think this issue is solved now.

BTW, the current parser is smarter and you don't need to pass `chunksize = 0`. Also, I added `hasheader = false` to automatically generate column names like X1, X2, etc.

```
julia> using TableReader
[ Info: Recompiling stale cache file /Users/kenta/.julia/compiled/v1.1/TableReader/EYKoh.ji for TableReader [70df011a-6618-58d7-8e16-3cf9e384cb47]

julia> @time df = readcsv("data/Performance_2016Q1.csv", delim = '|', hasheader = false);
 13.672620 seconds (13.58 M allocations: 6.054 GiB, 23.08% gc time)

julia> names(df)[1:4]
4-element Array{Symbol,1}:
 :X1
 :X2
 :X3
 :X4

```
