### ISSUE TITLE
Allowing quot=nothing

### ISSUE THREAD

**Issue by yurivish** [bicycle1885/TableReader.jl#48]
I have run into an interesting situation where my file contains all of the possible quote delimiters within it and the fields are unquoted. Is there a simple way to do the equivalent of setting the quotation character to `nothing`? I have not yet found a character that _doesn't_ appear in the file, otherwise I'd have added it to `ALLOWED_QUOTECHARS` to see what happens. Edit: Found one: `⬲` :)

The data are wiki pageviews: https://dumps.wikimedia.org/other/pagecounts-ez/, https://dumps.wikimedia.org/other/pagecounts-ez/merged/

**Comment by yurivish** [comment]
Ha, the simple hack of putting in a non-ASCII quot fails because it expects it to be castable to a UInt8. And fixing that immediate issue surfaces some dispatch signatures that need to be changed (`fillcolumn!`). Changing those enabled this to work, modulo some small invalid bytes in the file that I fixed via `sed`.

**Comment by bicycle1885** [comment]
Hi, I think #50 will work. `0xff` never occurs within valid UTF-8 text so we can use it as a proxy character.

**Comment by yurivish** [comment]
Great idea. Thank you!
