### ISSUE TITLE
Delimiter not detected on v0.4.0 on Windows 10

### ISSUE THREAD

**Issue by xiaodaigh** [bicycle1885/TableReader.jl#49]
Found an example where the delimiter of `'|'` is not detected

```julia
download("https://github.com/xiaodaigh/testing/raw/master/Performance_2003Q3.zip", "ok.zip")
run(`unzip -o ok.zip`)
using TableReader
path = "Performance_2003Q3.txt"
@time a = readcsv(path, hasheader = false); # does not work
@time a = readcsv(path, delimit = '|', hasheader = false); # works
```

**Comment by bicycle1885** [comment]
Automatic delimiter detection is a feature of `readdlm`, and not `readcsv`. `readcsv` still assumes that fields are delimited by the comma character. However, I may change the default behavior in the future.
