### ISSUE TITLE
Why another one?

### ISSUE THREAD

**Issue by xiaodaigh** [bicycle1885/TableReader.jl#5]
Is speed the main selling point here? I think should benchmark against R's `data.table::fread` which is a beast

**Comment by bicycle1885** [comment]
A short answer is CSV.jl and CSVFiles.jl cannot read a file I want to read. I've already filed an issue at CSV.jl (https://github.com/JuliaData/CSV.jl/issues/388). CSVFiles.jl takes indefinitely long time. This package can read the file within a few seconds:

```
julia> @time readcsv("data/GSM2230757_human1_umifm_counts.csv");
  3.951878 seconds (6.54 M allocations: 1.202 GiB, 9.19% gc time)

```

**Comment by xiaodaigh** [comment]
That's too bad :( hopefully one day all of these can be unified.

**Comment by bicycle1885** [comment]
Yeah, currently several Julia packages are not good at handling very wide tables that biologists often use. I want to fix that but it would require fixing the Julia compiler itself. Creating a new package for our requirements is much easier than that.
