### ISSUE TITLE
delimiter '|' is not allowed

### ISSUE THREAD

**Issue by xiaodaigh** [bicycle1885/TableReader.jl#6]
I tried `readcsv("c:/data/some.csv"; delim = '|')` and it gives error delimiter '|' is not allowed. Why not?

**Comment by bicycle1885** [comment]
Surely it should be allowed. I was lazy so I tried to make a sensible whitelist of delimiters using `ispunct`, but somewhat surprisingly `ispunct('|')` returns `false`. I will fix the whitelist soon.

**Comment by bicycle1885** [comment]
This is fixed by c12dfd06fc62302cf6f9ce384c1e590289cdb166.
